language: rust
sudo: false
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - 1.13.0
  - stable
  - beta
  - nightly

before_script:
  - pip install 'travis-cargo<0.2' --user

script:
  - travis-cargo test
  - travis-cargo --only stable doc

after_success:
  - travis-cargo coveralls --no-sudo --verify
